### ISSUE TITLE
Mongod user does not have permission to create directory

### ISSUE THREAD

**Issue by MrMMorris** [appelgriebsch/dockers#1]
I am trying to use your mongo container, but when I run it, I get a bunch of errors starting with:

```
Creating database path /data/db/b2773f90a13e.
mkdir: cannot create directory '/data/db/b2773f90a13e': Permission denied
```

This is most likely because the mongod user specified (https://github.com/appelgriebsch/dockers/blob/master/docker/mongodb/Dockerfile#L62) does not have permissions to create directories.

Am I doing something wrong?

Here is the Ansible tasks I am using to start the containers:

``` yaml
- name: create data container
  docker:
    name: data
    image: appelgriebsch/mongodb:2.6
    volumes: /data/db
    state: present

- name: run mongodb container
  docker:
    name: mongodb01
    image: appelgriebsch/mongodb:2.6
    env: "MONGO_DBDIR=/data/db,MONGO_BIND=0.0.0.0,MONGO_REPLSET=replica01"
    volumes_from: data
    publish_all_ports: True
    restart_policy: always
    state: started

- name: run mongodb container
  docker:
    name: mongodb02
    image: appelgriebsch/mongodb:2.6
    links:
      - mongodb01
    env: "MONGO_DBDIR=/data/db,MONGO_BIND=0.0.0.0,MONGO_REPLSET=replica02"
    volumes_from: data
    publish_all_ports: True
    restart_policy: always
    state: started
```
